test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  database: ItJobs_test
  username: app
  password: pass

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ItJobs
  host: 127.0.0.1
  username: app
  password: pass
